[workspace]
members = [ "crates/chainio/clients/avsregistry/",
"crates/chainio/clients/elcontracts/",
"crates/chainio/clients/eth/",
"crates/chainio/clients/fireblocks/",
"crates/contracts/bindings/",
"crates/chainio/utils/",
"crates/crypto/bn254/",
"crates/utils/",
"crates/crypto/bls/",
"crates/metrics/collectors/economic/",
"crates/metrics/collectors/rpc_calls/",
"crates/services/avsregistry/",
"crates/services/bls_aggregation/",
"crates/services/operatorsinfo/",
"crates/types/",
"crates/metrics/",
"crates/types/",
"examples/info-operator-service/",
"examples/bls-aggregation-service/"
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
authors = ["Eigen Layer contributors"]
rust-version = "1.76"
repository = "https://github.com/supernovahs/eigen-rs"
homepage = ""
license-file = "LICENSE.txt"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]
ethers =  "2.0.14"
ark-ff = "0.4.0"
eyre = "0.6.12"
reth = {git = "https://github.com/paradigmxyz/reth"}
prometheus-client = "0.22.2"
bn254 = {git = "https://github.com/sedaprotocol/bn254"}
eigen-metrics = {version = "0.0.1-alpha",  path = "crates/metrics/"}
serde = {version = "1.0.197" , features = ["derive"]}
eigen-chainio-utils = {path = "crates/chainio/utils/"}
eigen-client-avsregistry = {path = "crates/chainio/clients/avsregistry"}
eigen-client-elcontracts = {path = "crates/chainio/clients/elcontracts"}
eigen-client-eth = {path = "crates/chainio/clients/eth"}
eigen-client-fireblocks = {path = "crates/chainio/clients/fireblocks"}
eigen-contract-bindings = { path = "crates/contracts/bindings/"}
eigen-types = {path = "crates/types/"}
eigen-crypto-bls = {path = "crates/crypto/bls/"}
eigen-crypto-bn254 = {path = "crates/crypto/bn254/"}
eigen-utils = {path = "crates/utils/"}
eigen-metrics-collectors-economic = {path = "crates/metrics/collectors/economic"}
eigen-metrics-collectors-rpc-calls = {path = "crates/metrics/collectors/rpc_calls"}
eigen-services-avsregistry = {path = "crates/services/avsregistry"}
eigen-services-blsaggregation = {path = "crates/services/bls_aggregation"}
eigen-services-operatorsinfo = {path = "crates/services/operatorsinfo"}
info-operator-service = {path = "examples/info-operator-service"}
bls-aggregation-service = {path = "examples/bls-aggregation-service"}
tokio = {version = "1.37.0" , features = ["test-util", "full","sync"] }
futures-util = "0.3.30"
thiserror = "1.0"
tracing = "0.1.40"

#misc 
parking_lot = "0.12"

#alloy
alloy-chains = "0.1.15"
alloy-primitives = "0.7.2"
alloy-dyn-abi = "0.7.2"
alloy-sol-types = "0.7.2"
alloy-rlp = "0.3.4"
alloy-trie = "0.3.1"
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-anvil = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-trace = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-genesis = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "af788af", default-features = false, features = [
    "reqwest","ws"
] }
alloy-transport-http = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-eips = { git = "https://github.com/alloy-rs/alloy", default-features = false, rev = "af788af" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-contract = {git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-transport =  {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-transport-ws = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-rpc-client = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}